
#define SCRIBUS_VERSION_MAJOR 2
#define SCRIBUS_VERSION_MINOR 0
#define SCRIBUS_VERSION_MICRO 0
#define SCRIBUS_VERSION_TWEAK 0
#define SCRIBUS_VERSION_EXTRA ""

#define SCRIBUS_VERSION_STRING "2.0.0"
#define SCRIBUS_FULL_VERSION_STRING "2.0.0"

#define SCRIBUS_LEGAL_COPYRIGHT "Copyright (C) 2001-2026 by The Scribus Team"
